// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MediaTypeController from "./media_type_controller"
application.register("media-type", MediaTypeController)

import TracksController from "./tracks_controller"
application.register("tracks", TracksController)
